### ISSUE TITLE
THuman Dataset preprocess

### ISSUE THREAD

**Issue by mmmcn** [YuliangXiu/ICON#62] opened 2022-05-23 07:22 UTC
Hi, I found the program was running so slowly when I ran `bash render_batch.sh debug all`, I figured out it  stopped at `hits = mesh.ray.intersects_any (origins + delta * normals, vectors)`, and the number of rays is the millions, is that the reason why it was too slow?

**Comment by YuliangXiu** [comment] 2022-05-23 07:57
**Pyembree** is required for computing ray intersection inside trimesh (https://trimsh.org/), please uninstall and reinstall pyembree and trimesh, and then it should work well.

Same issue in [PIFu](https://github.com/shunsukesaito/PIFu/issues/26)

**Comment by mmmcn** [comment] 2022-05-24 03:50
thx，now `intersects_any()` works fine, but I ran into another problem:  
```shell
-> rndr = PRTRender(width=size, height=size, ms_rate=16, egl=egl)
(Pdb) c
Traceback (most recent call last):
  File "./render_single.py", line 125, in <module>
    rndr = PRTRender(width=size, height=size, ms_rate=16, egl=egl)
  File "/home/private/project/3d-holographic-reconstruction/ICON/scripts/./../lib/renderer/gl/prt_render.py", line 35, in __init__
    CamRender.__init__(self,
  File "/home/private/project/3d-holographic-reconstruction/ICON/scripts/./../lib/renderer/gl/cam_render.py", line 32, in __init__
    Render.__init__(self,
  File "/home/private/project/3d-holographic-reconstruction/ICON/scripts/./../lib/renderer/gl/render.py", line 96, in __init__
    glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE,
  File "/home/private/Software/anaconda3/envs/icon/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glTexImage2DMultisample,
	cArguments = (
		GL_TEXTURE_2D_MULTISAMPLE,
		16,
		GL_RGBA32F,
		512,
		512,
		GL_TRUE,
	)
)
```
Is PyOpenGL version or something else? my `PyOpenGL==3.1.6` and `PyOpenGL_accelerate==3.1.5`

**Comment by YuliangXiu** [comment] 2022-05-24 10:22
#60

**Comment by mmmcn** [comment] 2022-05-24 12:41
Sorry to bother you again, after running `bash render_batch.sh debug all` successfully, I got results below,
<table>
<tr>
<td><img src=https://cdn.jsdelivr.net/gh/mmmcn/cdn@master/img/202205241956885.png border=0></td>
<td><img src=https://cdn.jsdelivr.net/gh/mmmcn/cdn@master/img/202205241946334.png border=0></td>
<td><img src=https://cdn.jsdelivr.net/gh/mmmcn/cdn@master/img/202205241946899.png border=0></td>
<td><img src=https://cdn.jsdelivr.net/gh/mmmcn/cdn@master/img/202205241945617.png border=0></td>
</tr>
<tr>
<td>Snapshot on mesh</td>
<td>Normal(SMPL, Front)</td>
<td>Normal(Front)</td>
<td>RGB Image</td>
</tr>
</table>
I am confused why RGB image and normal image are incorrect

**Comment by YuliangXiu** [comment] 2022-05-24 17:10
I checked my rendering results, and they are correct. These kinds of artifacts are often caused by the disordered face topology, and should be resolved by `trimesh.load(...maintain_order=True)`. 

BTW, I am using `trimesh==3.9.35`

**Comment by mmmcn** [comment] 2022-05-25 01:34
Thank you so much for your reply! everything worked fine after I rebooted the mechine and ran the script again, though I'm not sure what caused this problem.

**Closed** 2022-05-25 01:34 UTC

**Comment by mmmcn** [comment] 2022-05-25 01:51
BTW, is there a way to get depth images that correspond to the RGB images?

**Comment by YuliangXiu** [comment] 2022-05-25 07:51
set `depth=True` in [render_single.py](https://github.com/YuliangXiu/ICON/blob/master/scripts/render_single.py#L56)
