### ISSUE TITLE
Error: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv on linuxinux 

### ISSUE THREAD

**Issue by MING410** [YuliangXiu/ICON#14] opened 2022-02-16 13:04 UTC
hi! 
I got this error on linux system with cuda==10.2.
Installed pytorch3d locally as recommended, 
python = 3.8.12
pytorch = 1.8.0
pytorch3d = 0.6.1
 and already installed bvh-distance-queries.

**Comment by YuliangXiu** [comment] 2022-02-16 13:48
Duplicate of #8 

This kind of error is always caused by the incompatibility between PyTorch and other libs dependent on PyTorch, e.g. PyTorch3D. You need to install PyTorch firstly, and then re-install other dependencies based on it.

**Closed** 2022-02-24 22:31 UTC

**Comment by YuliangXiu** [comment] 2022-03-07 03:08
@MING410 I have replaced the `bvh-distance-queries` with `PyTorch3D+Kaolin`, thus you don't need to install it anymore. Also, the CUDA version is not limited to 11.0.
